name: cimagen
description: "Image work"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_compare_slider: ^2.8.0
  exif: ^3.3.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  png_chunks_extract: ^1.0.2
  convert: ^3.1.1
  settings_ui: ^2.0.2
  file_picker: ^6.1.1
  photo_view: ^0.14.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  path: ^1.8.3
  mime: ^1.0.5
  feedback: ^3.0.0
  crypto: ^3.0.3
  json_annotation: ^4.8.1
  window_manager: ^0.3.8
  gap: ^3.0.1
  system_theme: ^2.3.1
  flutter_context_menu: ^0.1.3
  image: ^4.1.7
  dotted_border: ^2.1.0 #fucking flutter
  desktop_drop: ^0.4.4
  collection: ^1.18.0
  animated_text_kit: ^4.2.2
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  share_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
   - family: Montserrat
     fonts:
       - asset: fonts/montserrat-100-normal.ttf
         weight: 100
       - asset: fonts/montserrat-200-normal.ttf
         weight: 200
       - asset: fonts/montserrat-300-normal.ttf
         weight: 300
       - asset: fonts/montserrat-400-normal.ttf
         weight: 400
       - asset: fonts/montserrat-500-normal.ttf
         weight: 500
       - asset: fonts/montserrat-600-normal.ttf
         weight: 600
       - asset: fonts/montserrat-700-normal.ttf
         weight: 700
       - asset: fonts/montserrat-800-normal.ttf
         weight: 800
       - asset: fonts/montserrat-900-normal.ttf
         weight: 900
   - family: 'Open Sans'
     fonts:
       - asset: fonts/OpenSans-Light.ttf
         weight: 300
       - asset: fonts/OpenSans-Regular.ttf
         weight: 400
       - asset: fonts/OpenSans-Medium.ttf
         weight: 500
       - asset: fonts/OpenSans-SemiBold.ttf
         weight: 600
       - asset: fonts/OpenSans-Bold.ttf
         weight: 700
       - asset: fonts/OpenSans-ExtraBold.ttf
         weight: 800
